// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: api/proto/courier.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CourierResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	FullName string `protobuf:"bytes,3,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Dist     int32  `protobuf:"varint,4,opt,name=dist,proto3" json:"dist,omitempty"`
}

func (x *CourierResponse) Reset() {
	*x = CourierResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_courier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierResponse) ProtoMessage() {}

func (x *CourierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_courier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierResponse.ProtoReflect.Descriptor instead.
func (*CourierResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_courier_proto_rawDescGZIP(), []int{0}
}

func (x *CourierResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CourierResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CourierResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CourierResponse) GetDist() int32 {
	if x != nil {
		return x.Dist
	}
	return 0
}

type GetAllCouriersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllCouriersRequest) Reset() {
	*x = GetAllCouriersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_courier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllCouriersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCouriersRequest) ProtoMessage() {}

func (x *GetAllCouriersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_courier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCouriersRequest.ProtoReflect.Descriptor instead.
func (*GetAllCouriersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_courier_proto_rawDescGZIP(), []int{1}
}

type GetAllCouriersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Couriers []*CourierResponse `protobuf:"bytes,1,rep,name=couriers,proto3" json:"couriers,omitempty"`
}

func (x *GetAllCouriersResponse) Reset() {
	*x = GetAllCouriersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_courier_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllCouriersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCouriersResponse) ProtoMessage() {}

func (x *GetAllCouriersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_courier_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCouriersResponse.ProtoReflect.Descriptor instead.
func (*GetAllCouriersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_courier_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllCouriersResponse) GetCouriers() []*CourierResponse {
	if x != nil {
		return x.Couriers
	}
	return nil
}

type CreateCourierRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullName string `protobuf:"bytes,1,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Dist     int32  `protobuf:"varint,2,opt,name=dist,proto3" json:"dist,omitempty"`
	Type     string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *CreateCourierRequest) Reset() {
	*x = CreateCourierRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_courier_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCourierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourierRequest) ProtoMessage() {}

func (x *CreateCourierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_courier_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourierRequest.ProtoReflect.Descriptor instead.
func (*CreateCourierRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_courier_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCourierRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateCourierRequest) GetDist() int32 {
	if x != nil {
		return x.Dist
	}
	return 0
}

func (x *CreateCourierRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_api_proto_courier_proto protoreflect.FileDescriptor

var file_api_proto_courier_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x75, 0x72,
	0x69, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x69,
	0x65, 0x72, 0x73, 0x22, 0x65, 0x0a, 0x0f, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75,
	0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75,
	0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x69, 0x73, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x64, 0x69, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x4f, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x75,
	0x72, 0x69, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a,
	0x08, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x73, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x69,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x72,
	0x69, 0x65, 0x72, 0x73, 0x22, 0x5a, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f,
	0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x69, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x64, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x32, 0xab, 0x01, 0x0a, 0x08, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x73, 0x12, 0x53, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x73, 0x12,
	0x1f, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72,
	0x69, 0x65, 0x72, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x73, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x73, 0x2e, 0x43,
	0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c,
	0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_courier_proto_rawDescOnce sync.Once
	file_api_proto_courier_proto_rawDescData = file_api_proto_courier_proto_rawDesc
)

func file_api_proto_courier_proto_rawDescGZIP() []byte {
	file_api_proto_courier_proto_rawDescOnce.Do(func() {
		file_api_proto_courier_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_courier_proto_rawDescData)
	})
	return file_api_proto_courier_proto_rawDescData
}

var file_api_proto_courier_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_courier_proto_goTypes = []any{
	(*CourierResponse)(nil),        // 0: couriers.CourierResponse
	(*GetAllCouriersRequest)(nil),  // 1: couriers.GetAllCouriersRequest
	(*GetAllCouriersResponse)(nil), // 2: couriers.GetAllCouriersResponse
	(*CreateCourierRequest)(nil),   // 3: couriers.CreateCourierRequest
}
var file_api_proto_courier_proto_depIdxs = []int32{
	0, // 0: couriers.GetAllCouriersResponse.couriers:type_name -> couriers.CourierResponse
	1, // 1: couriers.Couriers.GetAllCouriers:input_type -> couriers.GetAllCouriersRequest
	3, // 2: couriers.Couriers.CreateCourier:input_type -> couriers.CreateCourierRequest
	2, // 3: couriers.Couriers.GetAllCouriers:output_type -> couriers.GetAllCouriersResponse
	0, // 4: couriers.Couriers.CreateCourier:output_type -> couriers.CourierResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_courier_proto_init() }
func file_api_proto_courier_proto_init() {
	if File_api_proto_courier_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_courier_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CourierResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_courier_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllCouriersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_courier_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllCouriersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_courier_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateCourierRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_courier_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_courier_proto_goTypes,
		DependencyIndexes: file_api_proto_courier_proto_depIdxs,
		MessageInfos:      file_api_proto_courier_proto_msgTypes,
	}.Build()
	File_api_proto_courier_proto = out.File
	file_api_proto_courier_proto_rawDesc = nil
	file_api_proto_courier_proto_goTypes = nil
	file_api_proto_courier_proto_depIdxs = nil
}
